/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package daw;

import conexion_http.ConexionHTTP;
import java.io.IOException;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import modelos.Huella;
import serviciojson.JsonService;

/**
 *
 * @author ERICK
 */
public class InterfazGreen extends javax.swing.JFrame {

    private Huella huella;
    private String url;
    private Imagen img = new Imagen();

    /**
     * Creates new form NewJFrame
     */
    public InterfazGreen() {
        initComponents();
        ImageIcon imagen1 = new ImageIcon("C:\\Users\\Usuario\\Desktop\\HuellaCarbono2\\src\\main\\java\\image\\sisiss.png");
        buscar.setIcon(imagen1);

//        this.setContentPane(img);
//        JPanelImage imagen = new JPanelImage(panelPrincipal, "../image/bosque.jpg");
//        panelPrincipal.add(imagen).repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        buscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        obtenerURL = new javax.swing.JTextField();
        renovable3 = new javax.swing.JTextField();
        verde_res = new javax.swing.JLabel();
        renovable_res = new javax.swing.JLabel();
        limpio_res = new javax.swing.JLabel();
        co2_res = new javax.swing.JLabel();
        FondoProblema = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscar.setBackground(new java.awt.Color(82, 149, 48));
        buscar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buscar.setForeground(new java.awt.Color(255, 255, 255));
        buscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        panelPrincipal.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 160, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Introduce la URL:");
        panelPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 150, 30));

        obtenerURL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        obtenerURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtenerURLActionPerformed(evt);
            }
        });
        panelPrincipal.add(obtenerURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 290, -1));

        renovable3.setEditable(false);
        renovable3.setText("www.websitecarbon.com");
        renovable3.setBorder(null);
        renovable3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renovable3ActionPerformed(evt);
            }
        });
        panelPrincipal.add(renovable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 711, 175, -1));

        verde_res.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        verde_res.setForeground(new java.awt.Color(255, 255, 255));
        panelPrincipal.add(verde_res, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 640, 30));

        renovable_res.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        renovable_res.setForeground(new java.awt.Color(255, 255, 255));
        panelPrincipal.add(renovable_res, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 720, 30));

        limpio_res.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        limpio_res.setForeground(new java.awt.Color(255, 255, 255));
        panelPrincipal.add(limpio_res, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 640, 30));

        co2_res.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        co2_res.setForeground(new java.awt.Color(255, 255, 255));
        panelPrincipal.add(co2_res, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 790, 30));

        FondoProblema.setBackground(new java.awt.Color(102, 102, 255));
        FondoProblema.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\HuellaCarbono2\\src\\main\\java\\image\\bosque_fondo.png")); // NOI18N
        FondoProblema.setText("jLabel1");
        FondoProblema.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                FondoProblemaComponentShown(evt);
            }
        });
        panelPrincipal.add(FondoProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 730));

        jLabel3.setText("jLabel3");
        panelPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel1.setText("jLabel1");
        panelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelPrincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void obtenerURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtenerURLActionPerformed
        // TODO add your handling code here:

        String urlBase = "https://api.websitecarbon.com/site?url=";

        url = obtenerURL.getText();

    }//GEN-LAST:event_obtenerURLActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        String urlBase = "https://api.websitecarbon.com/site?url=";

        // Metodo para almacenar la url
        obtenerURLActionPerformed(evt);

        try {
            String fichero = ConexionHTTP.peticionHttpGet(urlBase + url);

            huella = (Huella) JsonService.stringToPojo(fichero, Huella.class);

        } catch (IOException ife) {

        }
        // Formatear el número con dos decimales
        DecimalFormat df = new DecimalFormat("0.00");

        boolean verde = huella.getGreen();
        if (verde) {
            verde_res.setText("Esta página está concienciando con el medio ambiente.");
        } else {
            verde_res.setText("Esta página no está concienciada con el medio ambiente.");
        }
        ImageIcon imagen5 = new ImageIcon("C:\\Users\\Usuario\\Desktop\\HuellaCarbono2\\src\\main\\java\\image\\hojaVerde.png");
        verde_res.setIcon(imagen5);
       

        String limpio = huella.getCleanerThan().toString();
        
        double limpieza = huella.getCleanerThan();
        limpio_res.setText("Más limpio que: el " + limpio + "% de páginas web.");
        ImageIcon imagen6 = new ImageIcon("C:\\Users\\Usuario\\Desktop\\HuellaCarbono2\\src\\main\\java\\image\\mundo.png");
        limpio_res.setIcon(imagen6);
        


        double co2D = huella.getStatistics().getCo2().getGrid().getGrams();

        String co2 = df.format(co2D);

        co2_res.setText("Se produce un consumo de " + co2 + "g cada vez que alguien visita esta página web.");
        ImageIcon imagen4 = new ImageIcon("C:\\Users\\Usuario\\Desktop\\HuellaCarbono2\\src\\main\\java\\image\\iconoCO2.png");
        co2_res.setIcon(imagen4);

        double renovableD = huella.getStatistics().getCo2().getRenewable().getGrams();

        String renovable = df.format(renovableD);

        renovable_res.setText("El servidor que aloja esta página web funciona con energía renovable en un " + renovable + "%.");

        if (verde) {
            ImageIcon imagen2 = new ImageIcon("C:\\Users\\Usuario\\Desktop\\HuellaCarbono2\\src\\main\\java\\image\\renovGreen.png");
            renovable_res.setIcon(imagen2);
        } else {
            ImageIcon imagen3 = new ImageIcon("C:\\Users\\Usuario\\Desktop\\HuellaCarbono2\\src\\main\\java\\image\\renovRed.png");
            renovable_res.setIcon(imagen3);
        }

//        restoResultados.setText("Más limpio que: el " + limpio + "% de páginas web"
//                + "\tCO2: se produce " + co2 + "g cada vez que alguien visita esta página"
//                + "\nRenovable: " + renovable + " es renovable"  
//        );

    }//GEN-LAST:event_buscarActionPerformed

    private void renovable3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renovable3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_renovable3ActionPerformed

    private void FondoProblemaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_FondoProblemaComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_FondoProblemaComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoProblema;
    private javax.swing.JButton buscar;
    private javax.swing.JLabel co2_res;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel limpio_res;
    private javax.swing.JTextField obtenerURL;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextField renovable3;
    private javax.swing.JLabel renovable_res;
    private javax.swing.JLabel verde_res;
    // End of variables declaration//GEN-END:variables
}
